name: Python CI

on:
  push:
    paths:
      - '**.py'              # 當 Python 檔案有變更時觸發
  pull_request:              # 當發 PR 時觸發
  workflow_dispatch:         # 允許手動觸發

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pylint reviewdog

      - name: Run Flake8 (block syntax & critical issues)
        run: |
          flake8 --max-line-length=120 . > flake8.log || true
          cat flake8.log
          grep -E "E999|NameError" flake8.log && exit 1 || true

      - name: Run Pylint (block fatal errors only)
        run: find . -name "*.py" | xargs pylint --errors-only

      - name: Run Black (format check, advisory via PR comments)
        run: |
          black --check --diff . | reviewdog -f=diff -name="black" -reporter=github-pr-review -level=warning || true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Pylint (style check, advisory via PR comments)
        run: |
          find . -name "*.py" | xargs pylint --disable=all --enable=style,convention,warning,refactor | reviewdog -efm="%f:%l:%c: %m" -name="pylint-style" -reporter=github-pr-review -level=info
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests with pytest
        run: pytest --maxfail=5 --disable-warnings -v

  codeql:
    name: Analyze with CodeQL
    runs-on: ubuntu-latest
    needs: test
    permissions:
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
          queries: +security-and-quality

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt  # 如果有需求才打開

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
