name: Python CI

on:
  push:
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then
            echo "Found requirements.txt. Installing..."
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Skipping dependency installation."
          fi

      - name: Syntax check
        run: |
          echo "Running syntax check..."
          python -m compileall -q .

      - name: Runtime check (execute all .py)
        run: |
          echo "Running runtime check..."
          for file in $(find . -name "*.py"); do
            echo "Testing $file ..."
            python "$file"
          done

      - name: Run flake8 (non-blocking)
        continue-on-error: true
        run: |
          pip install flake8
          echo "Running flake8 linting..."
          flake8 . || true
