name: Python CI

on:
  push:
    paths:
      - '**.py'                  # 只偵測 Python 檔案

  workflow_dispatch:              # 允許手動觸發



jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pylint

      - name: Run Flake8
        run: flake8 --max-line-length=120 .

      - name: Run Black (Check for formatting issues)
        run: black --check --verbose .

      - name: Run Pylint
        run: pylint --max-line-length=120 **/*.py

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests with pytest
        run: pytest --maxfail=5 --disable-warnings -v

  codeql:
    name: Analyze with CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/setup-codeql@v2
        with:
          language: python

      - name: Build the code
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
