name: Python CI

on:
  push:
    paths:
      - '**.py'              # 當 Python 檔案有變更時觸發
  pull_request:              # 當發 PR 時觸發
  workflow_dispatch:         # 允許手動觸發

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pylint

      - name: Run Flake8
        run: flake8 --max-line-length=120 .

      - name: Run Black (Check for formatting issues)
        run: black --check --verbose .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests with pytest
        run: pytest --maxfail=5 --disable-warnings -v

  codeql:
    name: Analyze with CodeQL
    runs-on: ubuntu-latest
    needs: test
    permissions:
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
          queries: +security-and-quality

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt  # 如果有需求才打開

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
